node {
    stage('Clone') { // for display purposes
        // Clone the configurations repository
        cleanWs()
        git 'https://github.com/send2durai/advanced-terraform-2823489.git'   
    }
    stage('Download') {
        // Download Terraform
        sh label: '', script: 'curl https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip \
            --output terraform_0.12.29_darwin_amd64.zip \
             && unzip terraform_0.12.29_darwin_amd64.zip'
    }
   
